In [11]:
import sys
sys.path.append('/home/kasia/Python Projects/scrapping_die_borke')
import pandas as pd
import time
import sqlite3

In [2]:
def extract_float_from_string(string):
    l = [float(x) for x in re.findall("\d+\.\d+", string)]
    if len(l) == 1:
        return l[0]
    else:
        return l

url = 'https://www.surf-und-segelschule-mueggelsee.de/?Wetterdaten'

def download_weather_data(url):
    response = requests.get(url) # 
    html = response.content
    scraped = BeautifulSoup(html,'html.parser')
    return scraped

In [8]:
scraped = download_weather_data(url)

In [3]:
def parse_data(scraped):
    d = []
    for data in scraped.find('div',class_="tbis-layout-cell layout-item-old-1").find_all('tr'):
        d.append(data.text)
    mapping = {}
    mapping['lastupdate'] = parser.parse(d[0].split(': ')[1])
    mapping['temp'] = extract_float_from_string(d[2])
    mapping['wind'] = extract_float_from_string(d[3])[0]
    mapping['boen'] = extract_float_from_string(d[3])[1]
    mapping['niederschlag'] = extract_float_from_string(d[4])
    mapping['feuchte'] = int(re.findall("\d+\\d+", d[5])[0])
    mapping['luftdruck'] = extract_float_from_string(d[6])
    return mapping

In [ ]:
# testing parse_data

test_data = open('scraped_test.txt').read()
test_data = BeautifulSoup(test_data)


desired_wind = 10
desored_feuchte = 44

result = parse_data(test_data)

assert result['wind'] == desired_wind

In [4]:
def create_db(database_name):
    connection = sqlite3.connect(database_name)
    cursor = connection.cursor()
    #cursor.execute('DROP TABLE IF EXISTS weather')
    sql_command = """CREATE TABLE IF NOT EXISTS weather (
    id INTEGER PRIMARY KEY,
    lastupdate DATETIME,
    temp REAL,
    wind REAL,
    boen REAL,
    niederschlag REAL,
    feuchte REAL,
    luftdruck REAL)"""

    cursor.execute(sql_command)
    connection.close()
    
def insert_to_db_table(mapping,database_name):
    connection = sqlite3.connect(database_name)
    cursor = connection.cursor()
    sql_command = """INSERT INTO weather 
    (lastupdate, temp, wind, boen, 
    niederschlag, feuchte, luftdruck) 
    VALUES (:lastupdate,:temp,:wind,:boen,
    :niederschlag,:feuchte,:luftdruck)"""

    cursor.execute(sql_command,mapping)
    connection.commit()
    connection.close()

In [9]:
create_db('data/scrap_die_borke.db')
url = 'https://www.surf-und-segelschule-mueggelsee.de/?Wetterdaten'
while True:
    try:
        get_data(url,'data/scrap_die_borke.db')
        time.sleep(30)
    except Exception as e:
        print("File not accessible",e)

KeyboardInterrupt:

In [12]:
connection = sqlite3.connect("data/scrap_die_borke.db")
pd.read_sql("SELECT * FROM weather",connection)

,id,lastupdate,temp,wind,boen,niederschlag,feuchte,luftdruck
0,1,2020-09-16 17:22:22,27.6,8.7,14.8,0.0,41.0,1015.4
1,2,2020-09-16 17:23:21,27.6,8.7,14.8,0.0,41.0,1015.4
2,3,2020-09-16 17:23:21,27.6,8.7,14.8,0.0,41.0,1015.4
3,4,2020-09-16 17:24:21,27.6,7.8,14.8,0.0,41.0,1015.4
4,5,2020-09-16 17:24:21,27.6,7.8,14.8,0.0,41.0,1015.4
...,...,...,...,...,...,...,...,...
66,67,2020-09-16 18:56:21,25.3,2.5,7.0,0.0,53.0,1015.5
67,68,2020-09-16 18:56:21,25.3,2.5,7.0,0.0,53.0,1015.5
68,69,2020-09-16 18:56:21,25.3,2.5,7.0,0.0,53.0,1015.5
69,70,2020-09-16 18:57:21,25.3,2.5,7.0,0.0,55.0,1015.5
70,71,2020-09-16 18:57:21,25.3,2.5,7.0,0.0,55.0,1015.5

In [6]:
def get_data(url):
    scraped = download_weather_data(url)
    mapping = parse_data(scraped)
    insert_to_db_table(mapping,'data/scrap_die_borke.db')